### ISSUE TITLE
Working with modules

### ISSUE THREAD

**Issue by antarr** [elsoul/souls#323]
I'm trying to move as much of my existing rails application to souls. I'm running into errors when dealing with modules/concerns.

I was getting an error with 
```ruby
module Legiscan
  require 'legiscan/error'
  require 'legiscan/request'
  require 'legiscan/push'
```

Was able to fix it by moving those class definitions in the same file

But now I'm getting an error with my concerns. I'm getting this error
```ruby
NameError: uninitialized constant Voter

  include Voter
```

in my model
```ruby
class User < ApplicationRecord
  include Voter
  include Follower
  include Verifiable
  include Devise::JWT::RevocationStrategies::JTIMatcher
````

How can I import modules into my models?

**Comment by POPPIN-FUMI** [comment]
when did you get this error?
souls check? or souls s?

**Comment by antarr** [comment]
When running migrations `souls db migration`

**Comment by POPPIN-FUMI** [comment]
did you add `require` at `app.rb` ?
souls is using zeitwerk, you can add your modules at app.rb !

**Comment by antarr** [comment]
@POPPIN-FUMI Thanks that was it. Had to add `loader.push_dir("#{Dir.pwd}/app/models/concerns")`

**Comment by POPPIN-FUMI** [comment]
@antarr Cool! I'm glad to hear that! Happy coding!
